In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
np.array([1,2,3,4,5])*2

array([ 2,  4,  6,  8, 10])

In [4]:
x=np.array([1,2,3,4,5])

In [7]:
y=a=np.array([[1,2,3,4,5],[1,2,3,4,5]])

In [8]:
x+y

array([[ 2,  4,  6,  8, 10],
       [ 2,  4,  6,  8, 10]])

In [9]:
x*y

array([[ 1,  4,  9, 16, 25],
       [ 1,  4,  9, 16, 25]])

In [10]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [11]:
a+b

array([5, 7, 9])

In [12]:
b-a

array([3, 3, 3])

In [13]:
a*b

array([ 4, 10, 18])

In [14]:
a/b

array([0.25, 0.4 , 0.5 ])

In [15]:
y

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [16]:
y+[1,2,3,4,5]

array([[ 2,  4,  6,  8, 10],
       [ 2,  4,  6,  8, 10]])

In [17]:
np.log(np.array([1,2,3,4,5]))

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [18]:
np.exp(np.array([1,2,3,4,5]))

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [19]:
np.log10(np.array([1,2,3,4,5]))

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ])

In [ ]:
np.add()
np.subtract()
np.multiply()
np.divide()
np.power()

In [24]:
a=np.array([[1,2],[5,8]])
b=np.array([[4,5],[54,89]])

In [25]:
a

array([[1, 2],
       [5, 8]])

In [26]:
b

array([[ 4,  5],
       [54, 89]])

In [30]:
np.dot(a,b) # mu;ti

array([[112, 183],
       [452, 737]])

In [31]:
a.T

array([[1, 5],
       [2, 8]])

In [32]:
b.T

array([[ 4, 54],
       [ 5, 89]])

In [34]:
np.linalg.inv(a) ## inverse

array([[-4. ,  1. ],
       [ 2.5, -0.5]])

In [35]:
y

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [36]:
b

array([[ 4,  5],
       [54, 89]])

In [37]:
b=np.array([14,2,3,4,85])

In [38]:
np.sort(b)

array([ 2,  3,  4, 14, 85])

In [47]:
np.sort(b,axis=0)

array([ 2,  3,  4, 14, 85])

In [49]:
# input/output 
# csv,txt,npy,npz
# np.save()
# np.load()

In [50]:
b

array([14,  2,  3,  4, 85])

In [51]:
np.save("outfile",b)

In [52]:
np.load("outfile.npy")

array([14,  2,  3,  4, 85])

In [53]:
z=np.array([1,2,3,4,5])

In [55]:
np.savez("myfile2",z)

In [57]:
u=np.load("myfile2.npz")

In [58]:
u

NpzFile 'myfile2.npz' with keys: arr_0

In [59]:
np.array(u)

array(['arr_0'], dtype='<U5')